// Adapted from @linxin666/dsh-usage/src/host/http.ts (Apache-2.0), which is itself generated by
// scripts/sync-shared.mjs from shared/host/http.ts. Semantics preserved verbatim; see NOTICE.
// 家族路由共用的 JSON 体/响应助手：一个严格有界读取、一个宽松有界读取、一个 JSON 对象
// 收窄、一个 JSON 写出。此前这些在各路由文件里复制粘贴且契约漂移（上限 4 KiB~1 MiB、四种
// 溢出行为）。本文件由 `scripts/sync-shared.mjs` 从共享源生成，改共享源后重跑 sync。

import type {IncomingMessage, OutgoingHttpHeaders, ServerResponse} from 'node:http'

const DEFAULT_JSON_BODY_MAX_BYTES = 64 * 1024

// 家族默认 JSON 响应头；调用方可追加或覆盖。
const JSON_HEADERS = {
  'content-type': 'application/json; charset=utf-8',
  'referrer-policy': 'no-referrer',
} satisfies OutgoingHttpHeaders

// 严格读取：超过 maxBytes 抛 'body too large'，空/非法 JSON 抛 JSON.parse 错误。
export async function readBoundedJson(req: IncomingMessage, maxBytes: number): Promise<unknown> {
  const chunks: Buffer[] = []
  let size = 0
  for await (const chunk of req) {
    const buffer = chunk as Buffer
    size += buffer.length
    if (size > maxBytes) throw new Error('body too large')
    chunks.push(buffer)
  }
  return JSON.parse(Buffer.concat(chunks).toString('utf8'))
}

// 宽松读取：空体、非法 JSON 或超限（默认 64 KiB）时返回 null。溢出走 req.destroy()
// 而非 drain，调用方此后不得再读该请求；objectOnly 时非 JSON 对象也返回 null。
export async function readJsonBody(
  req: IncomingMessage,
  opts: { maxBytes?: number; objectOnly?: boolean } = {},
): Promise<unknown | null> {
  const maxBytes = opts.maxBytes ?? DEFAULT_JSON_BODY_MAX_BYTES
  const chunks: Buffer[] = []
  let size = 0
  for await (const chunk of req) {
    const buffer = chunk as Buffer
    size += buffer.length
    if (size > maxBytes) {
      req.destroy()
      return null
    }
    chunks.push(buffer)
  }
  const text = Buffer.concat(chunks).toString('utf8')
  if (text === '') return null
  try {
    const parsed: unknown = JSON.parse(text)
    if (opts.objectOnly && !isJsonObject(parsed)) return null
    return parsed
  } catch {
    return null
  }
}

function isJsonObject(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value)
}

export function asJsonObject(value: unknown): Record<string, unknown> | undefined {
  return isJsonObject(value) ? value : undefined
}

export function writeJson(
  res: ServerResponse,
  status: number,
  body: unknown,
  headers: OutgoingHttpHeaders = {},
): void {
  const payload = JSON.stringify(body)
  res.writeHead(status, { ...JSON_HEADERS, ...headers })
  res.end(payload)
}
