// Adapted from @linxin666/dsh-usage/src/host/loopback.ts (Apache-2.0), which is itself generated by
// scripts/sync-shared.mjs from shared/host/loopback.ts. Semantics preserved verbatim; see NOTICE.
// Loopback 信任栅栏，家族路由共用。范围（RFC 5735 IPv4 127/8、::1、IPv4-mapped
// ::ffff:127/8，与 remote-web-ui 的门禁一致）、localhost 主机名，加浏览器同源标记
// (sec-fetch-site / Origin)。本文件由 `scripts/sync-shared.mjs` 生成，改共享源后重跑 sync。

import type {IncomingMessage} from 'node:http'

export function isIPv4Loopback(v4: string): boolean {
  const parts = v4.split('.')
  return parts.length === 4
    && parts[0] === '127'
    && parts.every(part => /^\d{1,3}$/.test(part) && Number(part) <= 255)
}

export function isLoopbackAddress(address: string | undefined): boolean {
  if (address === undefined) return false
  const normalized = address.toLowerCase()
  if (normalized === '::1') return true
  if (normalized.startsWith('::ffff:')) return isIPv4Loopback(normalized.slice('::ffff:'.length))
  return isIPv4Loopback(normalized)
}

export function isLoopbackHostname(hostname: string): boolean {
  if (hostname === 'localhost' || hostname === '[::1]') return true
  return isIPv4Loopback(hostname)
}

// 请求级栅栏：socket 地址是权威判据，X-Forwarded-For 永不可信。
export function isLoopbackRequest(request: IncomingMessage): boolean {
  if (!isLoopbackAddress(request.socket.remoteAddress)) return false
  const host = request.headers.host
  if (typeof host !== 'string') return false
  let hostUrl: URL
  try {
    hostUrl = new URL('http://' + host)
  } catch {
    return false
  }
  if (!isLoopbackHostname(hostUrl.hostname)) return false
  if (request.headers['sec-fetch-site'] === 'cross-site') return false
  const origin = request.headers.origin
  if (origin === undefined) return true
  try {
    return new URL(origin).host === hostUrl.host
  } catch {
    return false
  }
}
